// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.Web.Models;

namespace MovieApp.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518134903_AddRoomBrightnessSettings")]
    partial class AddRoomBrightnessSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieApp.Web.Models.HomeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BalconyBrightness")
                        .HasColumnType("int");

                    b.Property<int>("BathroomBrightness")
                        .HasColumnType("int");

                    b.Property<int>("BedroomBrightness")
                        .HasColumnType("int");

                    b.Property<string>("ConnectionQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Countdown")
                        .HasColumnType("int");

                    b.Property<int>("HallBrightness")
                        .HasColumnType("int");

                    b.Property<double>("Humidity")
                        .HasColumnType("float");

                    b.Property<bool>("IsDuvarLightOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLightOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMotorRunning")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOkumaLightOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSarkitLightOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTavanLightOn")
                        .HasColumnType("bit");

                    b.Property<int>("KitchenBrightness")
                        .HasColumnType("int");

                    b.Property<string>("LastSyncTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LivingRoomBrightness")
                        .HasColumnType("int");

                    b.Property<string>("OperatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServoAngle")
                        .HasColumnType("int");

                    b.Property<int>("SetMinutes")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("HomeStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
